// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SistemZaRezervacijuKarata.Models;
using System;

namespace SistemZaRezervacijuKarata.Migrations
{
    [DbContext(typeof(SistemZaRezervacijuKarataContext))]
    [Migration("20180113124422_Sala")]
    partial class Sala
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemZaRezervacijuKarata.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Drzava");

                    b.Property<string>("DuzinaTranjanja");

                    b.Property<string>("Godina");

                    b.Property<string>("Naslov");

                    b.Property<string>("Opis");

                    b.Property<string>("OrgininalniNaslov");

                    b.Property<DateTime>("PocetakPrikazivanja");

                    b.Property<string>("SlikaUrl");

                    b.Property<string>("YoutubeUrl");

                    b.Property<string>("Zanr");

                    b.HasKey("ID");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("SistemZaRezervacijuKarata.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BrojSedista");

                    b.Property<string>("Naziv");

                    b.Property<string>("Tehnologija");

                    b.HasKey("ID");

                    b.ToTable("Sala");
                });
#pragma warning restore 612, 618
        }
    }
}
