// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SistemZaRezervacijuKarata.Models;
using System;

namespace SistemZaRezervacijuKarata.Migrations
{
    [DbContext(typeof(SistemZaRezervacijuKarataContext))]
    partial class SistemZaRezervacijuKarataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemZaRezervacijuKarata.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Drzava");

                    b.Property<string>("DuzinaTranjanja");

                    b.Property<string>("Godina");

                    b.Property<string>("Naslov");

                    b.Property<string>("Opis");

                    b.Property<string>("OrgininalniNaslov");

                    b.Property<DateTime>("PocetakPrikazivanja");

                    b.Property<string>("SlikaUrl");

                    b.Property<string>("YoutubeUrl");

                    b.Property<string>("Zanr");

                    b.HasKey("ID");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("SistemZaRezervacijuKarata.Models.Projekcija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Datum");

                    b.Property<int>("FilmId");

                    b.Property<int>("SalaId");

                    b.Property<int>("SlobodnoSedista");

                    b.Property<DateTime>("Vreme");

                    b.HasKey("ID");

                    b.HasIndex("FilmId");

                    b.HasIndex("SalaId");

                    b.ToTable("Projekcija");
                });

            modelBuilder.Entity("SistemZaRezervacijuKarata.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BrojSedista");

                    b.Property<string>("Naziv");

                    b.Property<string>("Tehnologija");

                    b.HasKey("ID");

                    b.ToTable("Sala");
                });

            modelBuilder.Entity("SistemZaRezervacijuKarata.Models.Projekcija", b =>
                {
                    b.HasOne("SistemZaRezervacijuKarata.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemZaRezervacijuKarata.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
